version: "3.8"

networks:
  monitoring:
    driver: bridge

volumes:
  grafana_data: {}
  loki_data: {}
  loki_wal: {}
  prometheus_data: {}

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    networks:
      - monitoring
    ports:
      - "3306:3306"
    volumes:
      - ./zabbix/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: carryontech
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: carryontech

  zabbix-server:
    image: zabbix/zabbix-server-mysql:ubuntu-5.0.1
    container_name: zabbix-server
    networks:
      - monitoring
    ports:
      - "10051:10051"
    volumes:
      - ./zabbix/alertscripts:/usr/lib/zabbix/alertscripts
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: carryontech
    depends_on:
      - mysql
    restart: always

  zabbix-frontend:
    image: zabbix/zabbix-web-apache-mysql:ubuntu-5.0.1
    container_name: zabbix-frontend
    networks:
      - monitoring
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: carryontech
      PHP_TZ: America/Sao_Paulo
    depends_on:
      - mysql
    restart: always

  zabbix-agent:
    image: zabbix/zabbix-agent2:alpine-5.0.1
    container_name: zabbix-agent
    networks:
      - monitoring
    ports:
      - "10050:10050"
    privileged: true
    volumes:
      - /var/run:/var/run
    environment:
      ZBX_HOSTNAME: Zabbix server
      ZBX_SERVER_HOST: zabbix-server
    restart: always

  grafana:
    image: grafana/grafana
    container_name: grafana
    networks:
      - monitoring
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - zabbix-server
      - loki
      - prometheus
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
    restart: always

  loki:
    image: grafana/loki:2.9.3
    container_name: loki
    networks:
      - monitoring
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yml
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yml
    restart: always

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    networks:
      - monitoring
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    restart: always
